export interface BikeModel {
    bikeId: number,
    vin: string,
    brand: string,
    model: string,
    year: number,
    category: string,
    displacement: number,
    power: number,
    torque: number,
    fuel: string,
    transmission: string,
    color: string,
    price: number,
    description: string,
    image: string,
    engineType: string,
    cooling: string,
    weight: number,
    createdAt: string,
    updatedAt: string | null,
}